/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { MYERC20, MYERC20Interface } from "../MYERC20";

const _abi = [
  {
    inputs: [],
    name: "MAX_SUPPLY",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class MYERC20__factory {
  static readonly abi = _abi;
  static createInterface(): MYERC20Interface {
    return new utils.Interface(_abi) as MYERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MYERC20 {
    return new Contract(address, _abi, signerOrProvider) as MYERC20;
  }
}
