/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ITreasuryInterface extends ethers.utils.Interface {
  functions: {
    "MAX_TOKEN_SUPPLY()": FunctionFragment;
    "currencyUsed()": FunctionFragment;
    "deposit(address,uint256)": FunctionFragment;
    "pToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_TOKEN_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currencyUsed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_TOKEN_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pToken", data: BytesLike): Result;

  events: {};
}

export class ITreasury extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ITreasuryInterface;

  functions: {
    MAX_TOKEN_SUPPLY(overrides?: CallOverrides): Promise<[BigNumber]>;

    currencyUsed(overrides?: CallOverrides): Promise<[string]>;

    deposit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pToken(overrides?: CallOverrides): Promise<[string]>;
  };

  MAX_TOKEN_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

  currencyUsed(overrides?: CallOverrides): Promise<string>;

  deposit(
    arg0: string,
    arg1: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MAX_TOKEN_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    currencyUsed(overrides?: CallOverrides): Promise<string>;

    deposit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    MAX_TOKEN_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    currencyUsed(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_TOKEN_SUPPLY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currencyUsed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
