/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface StakingContractInterface extends ethers.utils.Interface {
  functions: {
    "TOKEN_TO_STAKE()": FunctionFragment;
    "TOKEN_TO_STAKE_MAX_SUPPLY()": FunctionFragment;
    "setTotalClaimableReward(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "TOKEN_TO_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_TO_STAKE_MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTotalClaimableReward",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "TOKEN_TO_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_TO_STAKE_MAX_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTotalClaimableReward",
    data: BytesLike
  ): Result;

  events: {};
}

export class StakingContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakingContractInterface;

  functions: {
    TOKEN_TO_STAKE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_TO_STAKE_MAX_SUPPLY(overrides?: CallOverrides): Promise<[BigNumber]>;

    setTotalClaimableReward(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  TOKEN_TO_STAKE(overrides?: CallOverrides): Promise<string>;

  TOKEN_TO_STAKE_MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

  setTotalClaimableReward(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    TOKEN_TO_STAKE(overrides?: CallOverrides): Promise<string>;

    TOKEN_TO_STAKE_MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    setTotalClaimableReward(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    TOKEN_TO_STAKE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_TO_STAKE_MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    setTotalClaimableReward(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    TOKEN_TO_STAKE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOKEN_TO_STAKE_MAX_SUPPLY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setTotalClaimableReward(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
